Bug 658502 SH4: use REGNUM() to access the Register number in  asm_output() parameters This patch fixes the following compilation error(s) when NJ_VERBOSE is defined but DEBUG isn't:
    In member function ‘void nanojit::Assembler::SH4_add_imm(int, nanojit::Register)’:
    error: request for member ‘n’ in ‘Rx’, which is of non-class type ‘nanojit::Register’
    ...

Reported and fixed by: Anandha-kumar CHINNAIYAN <anandha.chinnaiyan@st.com>
---
 nanojit/NativeSH4-auto-generated.h |  426 ++++++++++++++++++------------------
 1 files changed, 213 insertions(+), 213 deletions(-)

This patch fixes the following compilation error(s) when NJ_VERBOSE is
defined but DEBUG isn't:

    In member function ‘void nanojit::Assembler::SH4_add_imm(int, nanojit::Register)’:
    error: request for member ‘n’ in ‘Rx’, which is of non-class type ‘nanojit::Register’
    ...

Reported and fixed by: Anandha-kumar CHINNAIYAN <anandha.chinnaiyan@st.com>
---
 nanojit/NativeSH4-auto-generated.h |  426 ++++++++++++++++++------------------
 1 files changed, 213 insertions(+), 213 deletions(-)